export const SITE = {
  name: "Rahi's Collection",
  tagline: "Clothes, jewellery & stationery for the whole family",
  description: "Silchar's beloved family boutique in Ghungoor. Sarees, kurtis, gents wear, kids wear, imitation jewellery, and stationery — all under one roof. Open Mon–Sat, 10 AM–8:30 PM.",
  url: "https://rahicollections.store",
  address: "Near SUBHASHINI MEDICARE, Ghungoor, Silchar 788014, Assam, India",
  phones: ["+91 87218 73064", "+91 86381 88525"],
  whatsapp: "https://wa.me/918721873064?text=Hi%20Rahi's%20Collection!",
  whatsappNumber: "918721873064",
  hours: "Mon–Sat · 10 AM – 8:30 PM",
  email: "rahiscollection.silchar@gmail.com",
  social: {
    instagram: "https://www.instagram.com/rahiscollection.silchar/",
    facebook: "https://facebook.com/rahicollections",
  },
  ogImage: "/og-image.jpg",
  keywords: [
    "clothes shop in Silchar",
    "saree shop Silchar",
    "boutique in Silchar",
    "Ladies wear Silchar",
    "Gents wear Silchar",
    "Kids wear Silchar",
    "men's wear Silchar",
    "men's clothing Silchar",
    "kids clothing Silchar",
    "kids toys Silchar",
    "imitation jewellery Silchar",
    "stationery shop Ghungoor",
    "stationery items Silchar",
    "school supplies Silchar",
    "gift items Silchar",
    "best boutique in Ghungoor",
    "Rahi's Collection",
    "Rahi's Collections",
    "Rahis Collections",
    "Rahi Collections",
    "Rahi Collection",
    "best clothing store Silchar",
    "kurtis Silchar",
    "sarees Silchar",
    "bridal jewellery Silchar",
  ],
} as const;
